#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only
# Regenerate the compact YUYV thumbnail embedded by the kernel module.

set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PROJECT_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
SOURCE="$PROJECT_DIR/assets/no-signal-penguin.png"
OUTPUT="$PROJECT_DIR/data/gc570d_no_signal_320x180.inc"
WORK_DIR=$(mktemp -d)
RAW="$WORK_DIR/no-signal-penguin-320x180.yuyv"
ARRAY="$WORK_DIR/no-signal-penguin-320x180.inc"

cleanup()
{
	rm -rf -- "$WORK_DIR"
}
trap cleanup EXIT HUP INT TERM

command -v ffmpeg >/dev/null 2>&1 || {
	echo "generate-no-signal-asset: ffmpeg is required" >&2
	exit 1
}
command -v xxd >/dev/null 2>&1 || {
	echo "generate-no-signal-asset: xxd is required" >&2
	exit 1
}
[ -f "$SOURCE" ] || {
	echo "generate-no-signal-asset: missing $SOURCE" >&2
	exit 1
}

ffmpeg -v error -y -i "$SOURCE" \
	-vf 'scale=320:180:flags=lanczos' \
	-pix_fmt yuyv422 -f rawvideo "$RAW"

xxd -i -n gc570d_no_signal_yuyv "$RAW" > "$ARRAY"
{
	printf '%s\n' '/* SPDX-License-Identifier: GPL-2.0-only */'
	printf '%s\n' '/* Generated by scripts/generate-no-signal-asset.sh; do not edit. */'
	awk '
		NR == 1 { sub(/^unsigned char/, "static const u8") }
		/^unsigned int gc570d_no_signal_yuyv_len/ {
			sub(/^unsigned int/, "static const unsigned int")
		}
		{ print }
	' "$ARRAY"
} > "$OUTPUT"

printf 'generated %s (%s bytes raw)\n' "$OUTPUT" "$(wc -c < "$RAW")"
