// SPDX-License-Identifier: GPL-2.0-only
/*
 * Low-level GC570D bridge helpers, interrupt handling, Xilinx register access,
 * and shared hardware diagnostics.
 */
#include "gc570d.h"
/* Default 3000-nit HDR-to-SDR curve generated by the official driver. */
#include "../data/gc570d_hdr_lut_3000.inc"


#define GC570D_I2C_IRQS (GC570D_IRQ_I2C0 | GC570D_IRQ_I2C1 | \
			 GC570D_IRQ_I2C2 | GC570D_IRQ_I2C3)
/* Let a control transaction survive a starved DMA1 descriptor and its reset. */
#define GC570D_CONTROL_IRQ_TIMEOUT_US 3000000

void gc570d_control_irq_prepare(struct gc570d_dev *gc, u32 irq)
{
	/* Drain an ISR which may already have sampled the previous completion. */
	writel(irq, gc->bar0 + GC570D_REG_IRQ_STATUS);
	synchronize_irq(gc->irq);
	atomic_andnot(irq, &gc->control_irq_seen);
	writel(irq, gc->bar0 + GC570D_REG_IRQ_STATUS);
}

int gc570d_control_irq_wait(struct gc570d_dev *gc, u32 irq,
				    u32 *observed_irq)
{
	u32 status;
	int ret;

	ret = readl_poll_timeout(gc->bar0 + GC570D_REG_IRQ_STATUS, status,
				 (status & irq) ||
				 (atomic_read(&gc->control_irq_seen) & irq),
				 10, GC570D_CONTROL_IRQ_TIMEOUT_US);
	*observed_irq = readl(gc->bar0 + GC570D_REG_IRQ_STATUS) |
		(u32)atomic_read(&gc->control_irq_seen);
	return ret;
}

void gc570d_control_irq_finish(struct gc570d_dev *gc, u32 irq)
{
	writel(irq, gc->bar0 + GC570D_REG_IRQ_STATUS);
	atomic_andnot(irq, &gc->control_irq_seen);
}



/* capture_lock serializes shared INTx ownership for every video/audio DMA. */
void gc570d_video_irq_get_locked(struct gc570d_dev *gc)
{
	if (gc->video_irq_users++ == 0)
		enable_irq(gc->irq);
}

void gc570d_video_irq_put_locked(struct gc570d_dev *gc)
{
	if (WARN_ON(!gc->video_irq_users))
		return;
	if (--gc->video_irq_users == 0)
		disable_irq(gc->irq);
}

struct gc570d_register {
	u32 offset;
	const char *name;
};

/* Registers observed being read by the official driver GC570D bridge implementation. */
static const struct gc570d_register gc570d_diagnostic_registers[] = {
	{ 0x0000, "firmware_version" },
	{ 0x000c, "reset_status" },
	{ 0x0010, "interrupt_status" },
	{ 0x0014, "audio_descriptor_index" },
	{ 0x0034, "interrupt_control" },
	{ 0x0038, "interrupt_mode" },
	{ 0x0040, "xilinx_reset_control" },
	{ 0x0144, "gc_event_2000" },
	{ 0x0150, "i2c3_clock" },
	{ 0x0154, "i2c3_slave" },
	{ 0x0158, "i2c3_address_length" },
	{ 0x015c, "i2c3_data_width" },
	{ 0x0160, "i2c3_address" },
	{ 0x0164, "i2c3_count" },
	{ 0x016c, "i2c3_read_fifo" },
	{ 0x0170, "i2c3_command" },
	{ 0x0174, "i2c3_status" },
	{ 0x01a4, "event_0800" },
	{ 0x01e4, "gc_event_1000" },
	{ 0x0180, "i2c0_clock" },
	{ 0x0184, "i2c0_slave" },
	{ 0x0188, "i2c0_address_length" },
	{ 0x018c, "i2c0_data_width" },
	{ 0x0190, "i2c0_address" },
	{ 0x0194, "i2c0_count" },
	{ 0x019c, "i2c0_read_fifo" },
	{ 0x01a0, "i2c0_command" },
	{ 0x01c0, "i2c1_clock" },
	{ 0x01c4, "i2c1_slave" },
	{ 0x01c8, "i2c1_address_length" },
	{ 0x01cc, "i2c1_data_width" },
	{ 0x01d0, "i2c1_address" },
	{ 0x01d4, "i2c1_count" },
	{ 0x01dc, "i2c1_read_fifo" },
	{ 0x01e0, "i2c1_command" },
	{ 0x0300, "video0_descriptor_index" },
	{ 0x0304, "video0_descriptor_control" },
	{ 0x0704, "aux_descriptor_control" },
	{ 0x0728, "aux_descriptor_offset" },
	{ 0x0b00, "video1_descriptor_index" },
	{ 0x0b04, "video1_descriptor_control" },
	{ 0x109c, "aux_line_count" },
};

irqreturn_t gc570d_irq_handler(int irq, void *data)
{
	struct gc570d_dev *gc = data;
	bool any_handled = false;
	unsigned int pass;

	/*
	 * A new source can become pending while another W1C source is being
	 * serviced.  Drain the bridge status before returning from this shared,
	 * level-triggered INTx handler so that an I2C completion cannot strand a
	 * simultaneously completing DMA descriptor.
	 */
	for (pass = 0; pass < 8; pass++) {
		u32 status = readl(gc->bar0 + GC570D_REG_IRQ_STATUS);
		u32 i2c_status;
		u32 control_status;
		u32 unknown;
		bool handled = false;

		/* An empty bridge status belongs to another device on shared INTx. */
		if (!status)
			break;

		i2c_status = status & GC570D_I2C_IRQS;
		control_status = status & (GC570D_IRQ_XILINX_INTC |
					   GC570D_I2C_IRQS);
		unknown = status & ~(GC570D_DMA0_FRAME_IRQ |
					 GC570D_DMA_FRAME_IRQ |
					 GC570D_AUDIO0_IRQ | GC570D_AUDIO_IRQ |
					 GC570D_VIDEO_TERM_IRQS |
					 GC570D_AUDIO_TERM_IRQS |
					 GC570D_IRQ_XILINX_INTC |
					 GC570D_I2C_IRQS);

		atomic64_inc(&gc->irq_total);
		if (status & GC570D_AUDIO_IRQ) {
			atomic64_inc(&gc->irq_audio);
			atomic_set(&gc->audio_irq_pending, 1);
			writel(GC570D_AUDIO_IRQ,
			       gc->bar0 + GC570D_REG_IRQ_STATUS);
			wake_up_interruptible(&gc->audio_wait);
			handled = true;
		}
		if (status & GC570D_AUDIO0_IRQ) {
			atomic64_inc(&gc->irq_audio);
			atomic64_inc(&gc->irq_audio0);
			atomic_set(&gc->audio0_irq_pending, 1);
			writel(GC570D_AUDIO0_IRQ,
			       gc->bar0 + GC570D_REG_IRQ_STATUS);
			wake_up_interruptible(&gc->audio0_wait);
			handled = true;
		}
		if (status & (GC570D_VIDEO_TERM_IRQS |
			      GC570D_AUDIO_TERM_IRQS)) {
			atomic64_inc(&gc->irq_audio_term);
			if (status & GC570D_AUDIO0_TERM_IRQ)
				atomic64_inc(&gc->irq_audio0_term);
			writel(status & (GC570D_VIDEO_TERM_IRQS |
					  GC570D_AUDIO_TERM_IRQS),
			       gc->bar0 + GC570D_REG_IRQ_STATUS);
			handled = true;
		}
		/*
		 * Windows acknowledges bridge-I2C completion in its ISR and passes
		 * the saved controller status to a DPC.  Preserve that ordering:
		 * synchronous Linux callers can observe control_irq_seen even if this
		 * ISR clears the global W1C bit before their polling loop reads it.
		 */
		if (i2c_status) {
			atomic_or(i2c_status, &gc->control_irq_seen);
			writel(i2c_status,
			       gc->bar0 + GC570D_REG_IRQ_STATUS);
		}
		if (control_status)
			handled = true;
		if (unknown) {
			atomic64_inc(&gc->irq_other);
			atomic_or(unknown, &gc->irq_other_status);
		}

		if (status & (GC570D_DMA0_FRAME_IRQ |
			      GC570D_DMA_FRAME_IRQ)) {
			u32 video_status = status & (GC570D_DMA0_FRAME_IRQ |
						    GC570D_DMA_FRAME_IRQ);
			bool complete_dma0 = false;

			atomic64_inc(&gc->irq_dma);
			if (video_status & GC570D_DMA0_FRAME_IRQ) {
				atomic64_inc(&gc->irq_dma0);
				WRITE_ONCE(gc->dma0_irq_status, status);
				if (READ_ONCE(gc->video0_streaming)) {
					unsigned long flags;
					u32 index = readl(gc->bar0 +
							  GC570D_DMA0_DESC_INDEX) & 7;

					spin_lock_irqsave(&gc->video0_qlock, flags);
					if (index >= 1 &&
					    index <= GC570D_DMA_BURST_FRAMES) {
						u8 next = (gc->video0_event_head + 1) %
							  ARRAY_SIZE(gc->video0_events);

						if (next == gc->video0_event_tail)
							gc->video0_event_overflow = true;
						else {
							gc->video0_events[gc->video0_event_head] =
								index - 1;
							gc->video0_event_head = next;
						}
					} else {
						gc->video0_event_overflow = true;
					}
					spin_unlock_irqrestore(&gc->video0_qlock,
							       flags);
					wake_up_interruptible(&gc->video0_wait);
				} else {
					/* A diagnostic descriptor starves after completion. */
					if (!READ_ONCE(gc->dma0_continuous))
						writel(0, gc->bar0 +
						       GC570D_DMA0_DESC_CONTROL);
					complete_dma0 = true;
				}
			}
			if (video_status & GC570D_DMA_FRAME_IRQ) {
				atomic64_inc(&gc->irq_dma1);
				writel(0, gc->bar0 + GC570D_DMA_DESC_CONTROL);
				WRITE_ONCE(gc->dma_irq_status, status);
			}
			writel(video_status,
			       gc->bar0 + GC570D_REG_IRQ_STATUS);
			if (complete_dma0 ||
			    (video_status & GC570D_DMA_FRAME_IRQ))
				complete(&gc->dma_completion);
			handled = true;
		}

		if (!handled)
			break;
		any_handled = true;

		/* Flush each pass's posted W1C writes before reading status again. */
		readl(gc->bar0 + GC570D_REG_IRQ_STATUS);
	}

	return any_handled ? IRQ_HANDLED : IRQ_NONE;
}

static int gc570d_registers_show(struct seq_file *s, void *unused)
{
	struct gc570d_dev *gc = s->private;
	size_t i;

	seq_printf(s, "pci=%s bar0_size=0x%llx\n", pci_name(gc->pdev),
		   (unsigned long long)gc->bar0_len);

	for (i = 0; i < ARRAY_SIZE(gc570d_diagnostic_registers); i++) {
		const struct gc570d_register *reg =
			&gc570d_diagnostic_registers[i];

		seq_printf(s, "0x%04x %-27s 0x%08x\n", reg->offset,
			   reg->name, readl(gc->bar0 + reg->offset));
	}

	return 0;
}
GC570D_DEFINE_SHOW_ATTRIBUTE(gc570d_registers);

static int gc570d_irq_stats_show(struct seq_file *s, void *unused)
{
	struct gc570d_dev *gc = s->private;

	seq_printf(s,
		   "total=%lld dma=%lld dma0=%lld dma1=%lld audio=%lld audio_term=%lld audio0=%lld audio0_term=%lld irq_users=%u other=%lld other_status=0x%08x\n",
		   atomic64_read(&gc->irq_total), atomic64_read(&gc->irq_dma),
		   atomic64_read(&gc->irq_dma0),
		   atomic64_read(&gc->irq_dma1),
		   atomic64_read(&gc->irq_audio),
		   atomic64_read(&gc->irq_audio_term),
		   atomic64_read(&gc->irq_audio0),
		   atomic64_read(&gc->irq_audio0_term),
		   READ_ONCE(gc->video_irq_users),
		   atomic64_read(&gc->irq_other),
		   (u32)atomic_read(&gc->irq_other_status));
	return 0;
}
GC570D_DEFINE_SHOW_ATTRIBUTE(gc570d_irq_stats);

struct gc570d_xilinx_register {
	u32 address;
	const char *name;
};

static const struct gc570d_xilinx_register gc570d_xilinx_registers[] = {
	{ 0x000000, "preprocess_mode" },
	{ 0x000004, "preprocess_control" },
	{ 0x000008, "preprocess_frequency" },
	{ 0x001000, "hdr_lut_first" },
	{ 0x001400, "hdr_lut_middle" },
	{ 0x0017fc, "hdr_lut_last" },
	{ 0x0000f4, "preprocess_id" },
	{ 0x0000f0, "preprocess_version" },
};

/* Raw input/status words sampled by CVPreprocessXilinx::GetInputState(). */
static const struct gc570d_xilinx_register gc570d_xilinx_input_registers[] = {
	{ 0x000080, "input_status_80" },
	{ 0x000084, "input_status_84" },
	{ 0x000088, "input_status_88" },
	{ 0x00008c, "input_status_8c" },
	{ 0x000090, "input_status_90" },
	{ 0x000091, "input_status_91" },
	{ 0x0000a1, "input_status_a1" },
};

int gc570d_xilinx_read32(struct gc570d_dev *gc, u32 address,
				u32 *value, u8 raw[4], u32 *last_irq,
				u32 *last_status)
{
	u32 irq_status;
	u32 fifo_value;
	u32 transaction_status;
	int ret;

	mutex_lock(&gc->i2c_lock);

	/* CVPreprocessXilinx is wired to logical bus 3 on GC570D. */
	writel(GC570D_I2C3_CLOCK_VALUE, gc->bar0 + GC570D_REG_I2C3_CLOCK);
	readl(gc->bar0 + GC570D_REG_I2C3_CLOCK);

	/* Clear a stale completion before programming a new read transaction. */
	gc570d_control_irq_prepare(gc, GC570D_IRQ_I2C3);
	writel(GC570D_I2C_XILINX_ADDR | 1, gc->bar0 + GC570D_REG_I2C3_SLAVE);
	writel(2, gc->bar0 + GC570D_REG_I2C3_ADDR_LEN); /* Three address bytes. */
	writel(3, gc->bar0 + GC570D_REG_I2C3_WIDTH);    /* Four-byte FIFO words. */
	writel(address, gc->bar0 + GC570D_REG_I2C3_ADDRESS);
	writel(1, gc->bar0 + GC570D_REG_I2C3_COUNT);
	writel(GC570D_I2C_CLEAR_COMMAND, gc->bar0 + GC570D_REG_I2C3_COMMAND);
	writel(GC570D_I2C_READ_COMMAND, gc->bar0 + GC570D_REG_I2C3_COMMAND);

	ret = gc570d_control_irq_wait(gc, GC570D_IRQ_I2C3, &irq_status);
	*last_irq = irq_status;
	*last_status = readl(gc->bar0 + GC570D_REG_I2C3_STATUS);
	if (ret) {
		writel(GC570D_I2C_CLEAR_COMMAND,
		       gc->bar0 + GC570D_REG_I2C3_COMMAND);
		gc570d_control_irq_finish(gc, GC570D_IRQ_I2C3);
		goto out_unlock;
	}

	transaction_status = *last_status;
	gc570d_control_irq_finish(gc, GC570D_IRQ_I2C3);
	if (!(transaction_status & GC570D_I2C_READ_OK)) {
		writel(GC570D_I2C_CLEAR_COMMAND,
		       gc->bar0 + GC570D_REG_I2C3_COMMAND);
		ret = -EIO;
		goto out_unlock;
	}

	/* The official driver closes the transaction before draining the read FIFO. */
	writel(GC570D_I2C_CLEAR_COMMAND,
	       gc->bar0 + GC570D_REG_I2C3_COMMAND);
	fifo_value = readl(gc->bar0 + GC570D_REG_I2C3_READ_FIFO);
	*value = fifo_value;
	raw[0] = fifo_value;
	raw[1] = fifo_value >> 8;
	raw[2] = fifo_value >> 16;
	raw[3] = fifo_value >> 24;

out_unlock:
	mutex_unlock(&gc->i2c_lock);
	return ret;
}

int gc570d_xilinx_write32(struct gc570d_dev *gc, u32 address,
				  u32 value)
{
	u32 irq_status;
	u32 transaction_status;
	int ret;

	mutex_lock(&gc->i2c_lock);
	writel(GC570D_I2C3_CLOCK_VALUE, gc->bar0 + GC570D_REG_I2C3_CLOCK);
	gc570d_control_irq_prepare(gc, GC570D_IRQ_I2C3);
	writel(GC570D_I2C_XILINX_ADDR, gc->bar0 + GC570D_REG_I2C3_SLAVE);
	writel(2, gc->bar0 + GC570D_REG_I2C3_ADDR_LEN);
	writel(3, gc->bar0 + GC570D_REG_I2C3_WIDTH);
	writel(address, gc->bar0 + GC570D_REG_I2C3_ADDRESS);
	writel(1, gc->bar0 + GC570D_REG_I2C3_COUNT);
	writel(GC570D_I2C_CLEAR_COMMAND, gc->bar0 + GC570D_REG_I2C3_COMMAND);
	writel(value, gc->bar0 + GC570D_REG_I2C3_WRITE_FIFO);
	writel(GC570D_I2C_WRITE_COMMAND, gc->bar0 + GC570D_REG_I2C3_COMMAND);

	ret = gc570d_control_irq_wait(gc, GC570D_IRQ_I2C3, &irq_status);
	transaction_status = readl(gc->bar0 + GC570D_REG_I2C3_STATUS);
	gc570d_control_irq_finish(gc, GC570D_IRQ_I2C3);
	if (!ret && !(transaction_status & GC570D_I2C_WRITE_OK))
		ret = -EIO;
	writel(GC570D_I2C_CLEAR_COMMAND, gc->bar0 + GC570D_REG_I2C3_COMMAND);
	mutex_unlock(&gc->i2c_lock);

	return ret;
}

int gc570d_xilinx_load_hdr_lut_3000(struct gc570d_dev *gc)
{
	size_t i;
	int ret;

	/*
	 * The official driver serializes the curve into 512 little-endian words and
	 * The official driver publishes them at Xilinx addresses 0x1000..0x17fc.
	 * The registry fallback in the official driver is 3000 nits; the included
	 * table exactly matches the official driver's result for that default.
	 */
	for (i = 0; i < ARRAY_SIZE(gc570d_hdr_lut_3000); i++) {
		ret = gc570d_xilinx_write32(gc, 0x1000 + i * sizeof(u32),
					     gc570d_hdr_lut_3000[i]);
		if (ret)
			return dev_err_probe(&gc->pdev->dev, ret,
				"Xilinx HDR LUT write failed at word %zu\n", i);
	}

	dev_info(&gc->pdev->dev,
		 "Xilinx 3000-nit HDR-to-SDR LUT loaded: words=%zu first=%08x middle=%08x last=%08x\n",
		 ARRAY_SIZE(gc570d_hdr_lut_3000), gc570d_hdr_lut_3000[0],
		 gc570d_hdr_lut_3000[ARRAY_SIZE(gc570d_hdr_lut_3000) / 2],
		 gc570d_hdr_lut_3000[ARRAY_SIZE(gc570d_hdr_lut_3000) - 1]);
	return 0;
}

static int gc570d_xilinx_registers_show(struct seq_file *s, void *unused)
{
	struct gc570d_dev *gc = s->private;
	u8 raw[4] = { 0 };
	u32 last_irq = 0;
	u32 last_status = 0;
	u32 value;
	size_t i;
	int ret;

	seq_puts(s, "# Read-only transactions through I2C3 slave 0x4e\n");
	for (i = 0; i < ARRAY_SIZE(gc570d_xilinx_registers); i++) {
		const struct gc570d_xilinx_register *reg =
			&gc570d_xilinx_registers[i];

		ret = gc570d_xilinx_read32(gc, reg->address, &value, raw,
					   &last_irq, &last_status);
		if (ret) {
			seq_printf(s,
				   "0x%06x %-20s error=%d irq=0x%08x status=0x%08x\n",
				   reg->address, reg->name, ret,
				   last_irq, last_status);
			continue;
		}

		seq_printf(s,
			   "0x%06x %-20s 0x%08x raw=%02x:%02x:%02x:%02x\n",
			   reg->address, reg->name, value,
			   raw[0], raw[1], raw[2], raw[3]);
	}

	/*
	 * The official driver brackets every live input query with register 0xf8 set
	 * to one and then zero.  Reproduce that snapshot edge and expose the
	 * underlying words without assigning undocumented field meanings yet.
	 */
	seq_puts(s, "# Official-driver live-input snapshot (f8: 1 -> 0)\n");
	ret = gc570d_xilinx_write32(gc, 0x0000f8, 1);
	if (ret) {
		seq_printf(s, "snapshot_begin error=%d\n", ret);
		return 0;
	}
	for (i = 0; i < ARRAY_SIZE(gc570d_xilinx_input_registers); i++) {
		const struct gc570d_xilinx_register *reg =
			&gc570d_xilinx_input_registers[i];

		ret = gc570d_xilinx_read32(gc, reg->address, &value, raw,
					   &last_irq, &last_status);
		if (ret) {
			seq_printf(s,
				   "0x%06x %-20s error=%d irq=0x%08x status=0x%08x\n",
				   reg->address, reg->name, ret,
				   last_irq, last_status);
			continue;
		}

		seq_printf(s,
			   "0x%06x %-20s 0x%08x raw=%02x:%02x:%02x:%02x\n",
			   reg->address, reg->name, value,
			   raw[0], raw[1], raw[2], raw[3]);
	}
	ret = gc570d_xilinx_write32(gc, 0x0000f8, 0);
	if (ret)
		seq_printf(s, "snapshot_end error=%d\n", ret);

	return 0;
}
GC570D_DEFINE_SHOW_ATTRIBUTE(gc570d_xilinx_registers);

static ssize_t gc570d_preprocess_enable_write(struct file *file,
					       const char __user *buffer,
					       size_t count, loff_t *position)
{
	struct gc570d_dev *gc = file->private_data;
	u8 raw[4];
	u32 last_irq;
	u32 last_status;
	u32 control;
	u32 verified;
	bool enable;
	int ret;

	ret = kstrtobool_from_user(buffer, count, &enable);
	if (ret)
		return ret;

	ret = gc570d_xilinx_read32(gc, 0x000004, &control, raw,
					 &last_irq, &last_status);
	if (ret)
		return ret;
	if (enable)
		control |= BIT(16);
	else
		control &= ~BIT(16);

	ret = gc570d_xilinx_write32(gc, 0x000004, control);
	if (ret)
		return ret;
	ret = gc570d_xilinx_read32(gc, 0x000004, &verified, raw,
					 &last_irq, &last_status);
	if (ret)
		return ret;
	if ((verified ^ control) & BIT(16))
		return dev_err_probe(&gc->pdev->dev, -EIO,
				     "preprocessor enable bit did not latch\n");

	dev_info(&gc->pdev->dev, "preprocessor %s, control=0x%08x\n",
		 enable ? "enabled" : "disabled", verified);
	return count;
}

const struct file_operations gc570d_preprocess_enable_fops = {
	.owner = THIS_MODULE,
	.open = simple_open,
	.write = gc570d_preprocess_enable_write,
	.llseek = noop_llseek,
};
